apiVersion: apps/v1
kind: Deployment
metadata:
  name: springeks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springeks
  template:
    metadata:
      labels:
        app: springeks
    spec:
      containers:
        - name: springeks
          image: 841007833247.dkr.ecr.us-east-1.amazonaws.com/kpgw-spre:docker-getwell-service-413
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /cardiacrehab/v3/health/status
spec:
  type: NodePort
  selector:
    app: springeks
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
