---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spring-jersey-pvc
  labels:
    app: spring-jersey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
