apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
commonLabels:
  env: spre
  tenant: kpgw
  app: springeks
patchesStrategicMerge:
  - spring-deployment-patch.yaml

patchesJson6902:
  - target:
      version: v1beta1
      kind: Ingress
      group: extensions
      name: spring-ingress
    path: certificate-patch.yaml
