apiVersion: apps/v1
kind: Deployment
metadata:
  name: springeks
  labels:
    app: springeks
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: {FULL_IMAGE_NAME_WITH_VERSION}
          name: springeks
